import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/queryProvider";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}

//INPUT - justify-center items-start px-4 py-3.5 text-base font-semibold leading-6 bg-white rounded-2xl border border-solid border-stone-200 text-stone-300 max-md:pr-5

// NF LOGO - https://i.imgur.com/8eAEryB.png

// Button justify-center px-6 py-3.5 text-lg font-semibold leading-6 text-black bg-black rounded-2xl max-md:px-5
